### ISSUE TITLE
Does anyone know what is causing this error? I'm following the guide to the letter and everything is set up. I have a standard install of the Wii U SDK tools from Nintendo and a Wii U Unity Build.

### ISSUE THREAD

**Issue by PseudonymousAnonymous** [RetroAndDev/WiiUCafeSDKDeluxe#1]
Each time I try to build a retail master image, I get this warning:
************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at WiiUCafeSDKDeluxe.MasteringWindow.RepackContentWithNus() in C:\Users\AGODFROY.NDSJ\GitHub\WiiUCafeSDKDeluxe\src\WiiUCafeSDKDeluxe\WiiUCafeSDKDeluxe\MasteringWindow.cs:line 254
   at WiiUCafeSDKDeluxe.MasteringWindow.CopyRawToNus() in C:\Users\AGODFROY.NDSJ\GitHub\WiiUCafeSDKDeluxe\src\WiiUCafeSDKDeluxe\WiiUCafeSDKDeluxe\MasteringWindow.cs:line 217
   at WiiUCafeSDKDeluxe.MasteringWindow.DecryptSourceFileDir() in C:\Users\AGODFROY.NDSJ\GitHub\WiiUCafeSDKDeluxe\src\WiiUCafeSDKDeluxe\WiiUCafeSDKDeluxe\MasteringWindow.cs:line 174
   at WiiUCafeSDKDeluxe.MasteringWindow.AfterCopyToWorkDir() in C:\Users\AGODFROY.NDSJ\GitHub\WiiUCafeSDKDeluxe\src\WiiUCafeSDKDeluxe\WiiUCafeSDKDeluxe\MasteringWindow.cs:line 109
   at WiiUCafeSDKDeluxe.Completedelegate.Invoke()
   at WiiUCafeSDKDeluxe.CustomFileCopier.Copy() in C:\Users\AGODFROY.NDSJ\GitHub\WiiUCafeSDKDeluxe\src\WiiUCafeSDKDeluxe\WiiUCafeSDKDeluxe\CustomFileCopier.cs:line 62
   at WiiUCafeSDKDeluxe.MasteringWindow.CopyVersionToWorkFolder(String versionFolder) in C:\Users\AGODFROY.NDSJ\GitHub\WiiUCafeSDKDeluxe\src\WiiUCafeSDKDeluxe\WiiUCafeSDKDeluxe\MasteringWindow.cs:line 104
   at WiiUCafeSDKDeluxe.MasteringWindow.ProcessDownloadImage(String dataFolder) in C:\Users\AGODFROY.NDSJ\GitHub\WiiUCafeSDKDeluxe\src\WiiUCafeSDKDeluxe\WiiUCafeSDKDeluxe\MasteringWindow.cs:line 75
   at WiiUCafeSDKDeluxe.MasteringWindow.StartProcess() in C:\Users\AGODFROY.NDSJ\GitHub\WiiUCafeSDKDeluxe\src\WiiUCafeSDKDeluxe\WiiUCafeSDKDeluxe\MasteringWindow.cs:line 133
   at WiiUCafeSDKDeluxe.Home.button15_Click(Object sender, EventArgs e) in C:\Users\AGODFROY.NDSJ\GitHub\WiiUCafeSDKDeluxe\src\WiiUCafeSDKDeluxe\WiiUCafeSDKDeluxe\Home.cs:line 311
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WiiUCafeSDKDeluxe
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Users/Pseudonymous/Documents/WiiUTestBuild/WiiUCafeSDKDeluxe/WiiUCafeSDKDeluxe.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///E:/Users/Pseudonymous/Documents/WiiUTestBuild/WiiUCafeSDKDeluxe/System.Text.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 4.6.31308.01
    CodeBase: file:///E:/Users/Pseudonymous/Documents/WiiUTestBuild/WiiUCafeSDKDeluxe/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///E:/Users/Pseudonymous/Documents/WiiUTestBuild/WiiUCafeSDKDeluxe/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///E:/Users/Pseudonymous/Documents/WiiUTestBuild/WiiUCafeSDKDeluxe/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///E:/Users/Pseudonymous/Documents/WiiUTestBuild/WiiUCafeSDKDeluxe/System.Text.Encodings.Web.DLL
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.28619.01
    CodeBase: file:///E:/Users/Pseudonymous/Documents/WiiUTestBuild/WiiUCafeSDKDeluxe/System.Buffers.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///E:/Users/Pseudonymous/Documents/WiiUTestBuild/WiiUCafeSDKDeluxe/System.Numerics.Vectors.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

**Comment by PseudonymousAnonymous** [comment]
It seems like its looking for something from a user directory of the author

**Comment by RetroAndDev** [comment]
Some other users from gbatemp reported me this problem from v1.0.0 to v1.1.0.
For you, it's a little bit different... It's a problem when repacking with NUSPacker.
I will investigate when I will come back from vacations on Monday.

**Comment by PseudonymousAnonymous** [comment]
> Some other users from gbatemp reported me this problem from v1.0.0 to v1.1.0. For you, it's a little bit different... It's a problem when repacking with NUSPacker. I will investigate when I will come back from vacations on Monday.

Thank you, I am very glad that you are still an active dev on this project, given that a lot of attention has moved from this platform :)

**Comment by RetroAndDev** [comment]
If you moved to Wii U you can check my Tutorial on GBATemp about how to make a Unity Wii U game (go from the read me tutorial and go on my profile you will see it).

**Comment by PseudonymousAnonymous** [comment]
Absolutely! I've been collecting and archiving all the info I can about this platform before it's removed or lost

**Comment by PseudonymousAnonymous** [comment]
I will say, out of everything I've found, you have created the best documentation I can find on Unity for Wii U. I used your first guide to download my environment off the Dev Portal and build the game from Unity. Now, I just need it to be able to run on a retail console.

**Comment by RetroAndDev** [comment]
I am making some improvements on WiiUCafeSDKDeluxe for the v2. I will re-code NUSPacker and Kii U Generator in C# to remove the decency of Java and Python. Here is the other improvements I will do for v2 :
TitleID Generation
- New installation method (with a setup executable)
- Bug fixing
- An application icon
- Support of shortcut
- Better speed
- A brand-new tutorial
- Support of meta icons and splash screen

I will release the next part of the tutorial about making and installing Build on Retail Wii U with SCT when v2 will be relased

**Comment by RetroAndDev** [comment]
I investigated a little bit and your issue is one of these two options : 
 - NUSPacker.jar does not exist in /Tools/ folder (located in the .exe folder)
 - Your java.exe is not specified... Check your settings and make sure that JDK/JRE points to a valid java.exe (JDK 18.0.2.1 works and +)
 Tell me if one of the options worked or not for you.
 Note : What version of WiiSDK Deluxe are you using ?

**Comment by PseudonymousAnonymous** [comment]
I'm using v1.1.0. The folder labeled tools has NUSPacker.jar inside it. In fact, one of the first things I did was track down the NUSPacker repository and replaced the jar file inside the folder. Inside the Wii U SDK Deluxe itself, my Java path is listed by default and it's a valid installation. I tested my java version and it seems to have worked. Currently, to make my retail builds, I have to do it by hand using a batch file I made and a copy of CDcrypt. I unpack my unity install image build using CDcrypt and repack it using the batch file that runs NUSPacker with some arguments. This works, and I can install my game on my retail Wii U and Cemu. Here is the command I am using for the Batch for NUSPacker:
java -jar NUSPacker.jar  -in "E:\Users\Pseudonymous\Documents\WiiUTestBuild\Unpacked" -out "E:\Wii U TRUE BUILD" -encryptionKey DFFADCC1B2FDB21B7270ACC1EEAEBDD6 -encryptKeyWith D7B00402659BA2ABD2CB0DB27FA2B656 -skipXMLParsing -appType 80000000 -OSVersion 000500101000400A -tID 0005000011000000

**Comment by RetroAndDev** [comment]
I am back from vacations, I will see that a little bit today.
Tell me what is the full path to the WiiUCafeSDKDeluxe executable. I have a little idea, I think that possibly, the tool is case-sensitive for process paths... Or in some configurations...

**Comment by RetroAndDev** [comment]
I make a new release (v1.1.1) with advanced debugging (tools path checking/python/Java checking). Download it from Release Page and replace the WiiUCafeSDKDeluxe folder with this version. On launch this version will check all paths (and display it in logs). If one tools (CDecrypt/NUSPacker/keygen.py/Java/Python) is missing the tools will alert and display the path where it's missing. Tell me what tool is missing and his path

**Comment by RetroAndDev** [comment]
Fixed in latest release
